/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSectionRouteImport } from './routes/admin/$section'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminFeesRouteImport } from './routes/admin/fees'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as LoginParentRouteImport } from './routes/login.parent'
import { Route as LoginStaffRouteImport } from './routes/login.staff'
import { Route as LoginStudentRouteImport } from './routes/login.student'
import { Route as ParentIndexRouteImport } from './routes/parent/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffSectionRouteImport } from './routes/staff/$section'
import { Route as StaffAttendanceRouteImport } from './routes/staff/attendance'
import { Route as StaffMarksRouteImport } from './routes/staff/marks'
import { Route as StudentIndexRouteImport } from './routes/student/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/admin/$section',
  path: '/admin/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/admin/fees',
  path: '/admin/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LoginRoute,
} as any)
const LoginParentRoute = LoginParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => LoginRoute,
} as any)
const LoginStaffRoute = LoginStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => LoginRoute,
} as any)
const LoginStudentRoute = LoginStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => LoginRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSectionRoute = StaffSectionRouteImport.update({
  id: '/staff/$section',
  path: '/staff/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/staff/attendance',
  path: '/staff/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMarksRoute = StaffMarksRouteImport.update({
  id: '/staff/marks',
  path: '/staff/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/parent': typeof LoginParentRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/staff/$section': typeof StaffSectionRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/marks': typeof StaffMarksRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/parent': typeof LoginParentRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/staff/$section': typeof StaffSectionRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/marks': typeof StaffMarksRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/parent': typeof ParentIndexRoute
  '/staff': typeof StaffIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/parent': typeof LoginParentRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/staff/$section': typeof StaffSectionRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/marks': typeof StaffMarksRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/$section'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/register'
    | '/login/admin'
    | '/login/parent'
    | '/login/staff'
    | '/login/student'
    | '/staff/$section'
    | '/staff/attendance'
    | '/staff/marks'
    | '/admin/'
    | '/login/'
    | '/parent/'
    | '/staff/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/admin/$section'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/register'
    | '/login/admin'
    | '/login/parent'
    | '/login/staff'
    | '/login/student'
    | '/staff/$section'
    | '/staff/attendance'
    | '/staff/marks'
    | '/admin'
    | '/login'
    | '/parent'
    | '/staff'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/$section'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/register'
    | '/login/admin'
    | '/login/parent'
    | '/login/staff'
    | '/login/student'
    | '/staff/$section'
    | '/staff/attendance'
    | '/staff/marks'
    | '/admin/'
    | '/login/'
    | '/parent/'
    | '/staff/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminSectionRoute: typeof AdminSectionRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  StaffSectionRoute: typeof StaffSectionRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffMarksRoute: typeof StaffMarksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ParentIndexRoute: typeof ParentIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/admin/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/parent': {
      id: '/login/parent'
      path: '/parent'
      fullPath: '/login/parent'
      preLoaderRoute: typeof LoginParentRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/staff': {
      id: '/login/staff'
      path: '/staff'
      fullPath: '/login/staff'
      preLoaderRoute: typeof LoginStaffRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/student': {
      id: '/login/student'
      path: '/student'
      fullPath: '/login/student'
      preLoaderRoute: typeof LoginStudentRouteImport
      parentRoute: typeof LoginRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$section': {
      id: '/staff/$section'
      path: '/staff/$section'
      fullPath: '/staff/$section'
      preLoaderRoute: typeof StaffSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/attendance': {
      id: '/staff/attendance'
      path: '/staff/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/marks': {
      id: '/staff/marks'
      path: '/staff/marks'
      fullPath: '/staff/marks'
      preLoaderRoute: typeof StaffMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginAdminRoute: typeof LoginAdminRoute
  LoginParentRoute: typeof LoginParentRoute
  LoginStaffRoute: typeof LoginStaffRoute
  LoginStudentRoute: typeof LoginStudentRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAdminRoute: LoginAdminRoute,
  LoginParentRoute: LoginParentRoute,
  LoginStaffRoute: LoginStaffRoute,
  LoginStudentRoute: LoginStudentRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminSectionRoute: AdminSectionRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  StaffSectionRoute: StaffSectionRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffMarksRoute: StaffMarksRoute,
  AdminIndexRoute: AdminIndexRoute,
  ParentIndexRoute: ParentIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
